/**
 * One-shot inserter for an authored Markdown digest row.
 *
 * Writes directly to the `digests` table — same place the scheduled daily/
 * weekly/monthly digests land — so the row shows on /digests. Used for
 * event-driven analytical digests (e.g. an earnings deep-dive) that are
 * authored by hand rather than generated by run-digest.ts on a cron.
 *
 * Usage:
 *   npm exec tsx -- --env-file=.env.local scripts/insert-digest.ts \
 *     --md /path/to/body.md \
 *     --period event \
 *     --period-start 2026-05-14 \
 *     --period-end 2026-05-14 \
 *     --item-ids "4615,4618,4619,..."
 */
import { readFileSync } from "node:fs";
import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { digests } from "@/db/schema";

interface Args {
  md: string;
  period: string;
  periodStart: string; // YYYY-MM-DD
  periodEnd: string; // YYYY-MM-DD
  itemIds: number[];
  model?: string;
}

function parseArgs(argv: string[]): Args {
  const out: Partial<Args> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = argv[i + 1];
    if (a === "--md") {
      out.md = next;
      i++;
    } else if (a === "--period") {
      out.period = next;
      i++;
    } else if (a === "--period-start") {
      out.periodStart = next;
      i++;
    } else if (a === "--period-end") {
      out.periodEnd = next;
      i++;
    } else if (a === "--item-ids") {
      out.itemIds = next.split(",").map((s) => Number(s.trim())).filter(Number.isFinite);
      i++;
    } else if (a === "--model") {
      out.model = next;
      i++;
    }
  }
  if (!out.md || !out.period || !out.periodStart || !out.periodEnd) {
    throw new Error(
      "missing required arg (--md, --period, --period-start, --period-end)",
    );
  }
  return { ...out, itemIds: out.itemIds ?? [] } as Args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const bodyMd = readFileSync(args.md, "utf8");
  const start = new Date(`${args.periodStart}T00:00:00Z`);
  const end = new Date(`${args.periodEnd}T00:00:00Z`);
  if (isNaN(start.getTime()) || isNaN(end.getTime())) {
    throw new Error(`bad date: --period-start=${args.periodStart} --period-end=${args.periodEnd}`);
  }

  // Dedup on the table's unique (period, period_start) index.
  const dup = await db
    .select({ id: digests.id })
    .from(digests)
    .where(and(eq(digests.period, args.period), eq(digests.periodStart, start)))
    .limit(1);
  if (dup.length > 0) {
    console.log(
      `[skip] digest already present at (period=${args.period}, period_start=${args.periodStart}) as id=${dup[0].id}`,
    );
    return;
  }

  const [row] = await db
    .insert(digests)
    .values({
      period: args.period,
      periodStart: start,
      periodEnd: end,
      summaryMd: bodyMd,
      itemIds: args.itemIds,
      model: args.model ?? "claude-opus-4-7 (manual)",
    })
    .returning({ id: digests.id });

  console.log(`[ok] inserted digest id=${row.id}`);
  console.log(`     period=${args.period}  period_start=${args.periodStart}`);
  console.log(`     body length=${bodyMd.length} chars; item_ids count=${args.itemIds.length}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("fatal:", err);
    process.exit(1);
  });
